### ISSUE TITLE
Alaska

### ISSUE THREAD

**Issue by kofron** [deanputney/earlyvoting#61]
* Text is malformatted under can I vote by mail and should be bullets

**Comment by deanputney** [comment]
I am realizing now that formatting is not our only issue here. Alaska has content under the VBM section which _should_, the way I read it, appear under the In Person Voting section.

I propose:

1.  We read through these in the sheet and move parts of the text from `early-voting-notes` to `early-voting-in-person-info-manual` and parts to `vbm-absentee-ballot-rules-manual` as appropriate.
2. We do away with `early-voting-by-mail-info-manual` and `early-voting-by-mail-info-combined` as they appear to be merely cloning `early-voting-notes-combined` and conflating VBM and In Person Early Voting.

This is not a small change... Might take a few hours to really do properly if this is the path we want to take. I wish there was a better way to edit these spreadsheets.

This comment creates issue #90

**Comment by deanputney** [comment]
Spreadsheet updated, dependent on #89
